### ISSUE TITLE
Bugs with newest version (2015-06-22)

### ISSUE THREAD

**Issue by individuell** [bakatz/SpotMute#1]
In SpotifyInformation.cs:

Line 63: 
Replace the long dash with a short dash (see comment), since the current version uses a short dash

Line 68: 
Replace the line...
String artist = theItem[0].Remove(0, 10).Trim();
...with...
String artist = theItem[0].Trim();

Since there is no "Spotify - " string in the title anymore

---

by the way I also just came across a .net wrapper for the newest Web API, might be useful here
https://github.com/JohnnyCrazy/SpotifyAPI-NET

**Comment by bakatz** [comment]
Good catch. I'll look at fixing this soon

Thanks

**Comment by bakatz** [comment]
Looking into this now. Running into some issues with the piece of code that tries to attach to the necessary spotify.exe process (the one with the audio session initalized). Need to work around that first to see if your fix is correct.

Thanks

**Comment by bakatz** [comment]
Fixed the issue with attaching to the wrong process, and your fix is indeed correct, but I've identified another issue where spotmute isn't getting the window title changes properly, hence when the song changes, spotmute has no idea about the change. This will take some additional investigation, so I will go ahead and close this issue out and open a new one to track the window title issue.

Thanks again for reporting this. You can see the change in the latest version of the code.
